// Random facts shown during HARD difficulty waits.
// Pure flavor text — none of these hint at timing, position, or game state.
const FACTS = [
  "A group of crows is called a murder.",
  "Honey never spoils.",
  "Octopuses have three hearts.",
  "Bananas are botanically classified as berries.",
  "The Eiffel Tower grows taller in summer heat.",
  "A bolt of lightning is hotter than the surface of the sun.",
  "Sharks existed before trees.",
  "Wombat droppings are cube-shaped.",
  "Venus is the only planet that spins clockwise.",
  "The shortest war in history lasted 38 minutes.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "There are more stars in the universe than grains of sand on Earth.",
  "A day on Venus is longer than its year.",
  "Polar bears have black skin under their white fur.",
  "The inventor of the Frisbee was turned into a Frisbee after he died.",
  "Cleopatra lived closer in time to the Moon landing than to the building of the pyramids.",
  "A single cloud can weigh more than a million pounds.",
  "Some turtles can breathe through their butts.",
  "The first computer bug was an actual moth.",
  "Hot water freezes faster than cold water under certain conditions.",
  "Butterflies can see ultraviolet light invisible to humans.",
  "There is a species of jellyfish that is biologically immortal.",
  "The human nose can detect over a trillion different scents.",
  "A bolt of static electricity can measure up to 3,000 volts.",
  "Mount Everest grows about 4 millimeters every year.",
  "Cows have best friends and get stressed when separated.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "An octopus can taste light with its skin.",
  "Saturn's moon Titan has lakes made of liquid methane.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "A flock of flamingos is called a flamboyance.",
  "Glass takes one million years to decompose.",
  "Scotland's national animal is the unicorn.",
  "The first oranges were not orange — they were green.",
  "Some metals are so reactive they explode on contact with water.",
  "The dot over a lowercase 'i' is called a tittle.",
  "Starfish do not have brains.",
  "Earth's core is almost as hot as the surface of the sun.",
  "A single strand of spaghetti is called a spaghetto.",
  "Most of a star's mass is hydrogen and helium.",
  "Koalas have fingerprints almost identical to humans.",
  "It rains diamonds on Jupiter and Saturn.",
  "The unicorn is one of the few mythical creatures with no confirmed sighting in any culture before written history.",
  "Slugs have four noses.",
  "A blue whale's heart is the size of a small car.",
  "Some bamboo species can grow nearly a meter in a single day.",
  "A 'jiffy' is an actual unit of time — 1/100th of a second.",
  "The total weight of ants on Earth roughly equals the total weight of humans.",
  "Lightning strikes the Earth about 8 million times a day.",
  "An adult human body contains around 37 trillion cells."
];
